<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Basic Invoices</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/basicinvoices/basicinvoices" target="_blank">Basic Invoices</a>.
        You are currently running Basic Invoices version <?= \BasicInvoices\Module::VERSION ?>.
        This is the starting point for building Basic Invoices on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/basicinvoices/basicinvoices" target="_blank">Fork Basic Invoices on GitHub &raquo;</a></p>
</div>
